version: "3.9"

services:
  app:
    &app
    container_name: components_structure
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        APP_USER_ID: ${APP_USER_ID}
    env_file: .env
    volumes:
      - .:/home/components_structure-user/components_structure:cached
      - ~/.ssh:/home/components_structure-user/.ssh
      - bundle:/bundle
      - rails_cache:/home/components_structure-user/components_structure/tmp/cache
      - node_modules:/home/components_structure-user/components_structure/node_modules
      - ~/.gitconfig:/etc/gitconfig
    tmpfs:
      - /tmp
    ports:
      - "3000:3000"
    depends_on:
      - development_db
      - test_db
    networks:
      - components_structure_private_network
    entrypoint: [ "/home/components_structure-user/components_structure/docker/entrypoint.sh" ]
    command: [ "rails", "server", "-b", "0.0.0.0", "-p", "3000" ]

  development_db:
    &development_db
    container_name: components_structure_development_db
    image: postgres:alpine
    env_file: .env
    volumes:
      - development_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DEVELOPMENT_DB_NAME}
      POSTGRES_USER: ${DEVELOPMENT_DB_USERNAME}
      POSTGRES_PASSWORD: ${DEVELOPMENT_DB_PASSWORD}
    networks:
      - components_structure_private_network
    restart: always

  test_db:
    <<: *development_db
    container_name: components_structure_test_db
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USERNAME}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    volumes:
      - test_db:/var/lib/postgresql/data


  redis:
    image: redis:alpine
    container_name: components_structure_redis
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-16379}:6379"
    env_file: .env
    restart: always
    networks:
      - components_structure_private_network

  worker:
    <<: *app
    container_name: components_structure_worker
    command: bundle exec sidekiq
    depends_on:
      - app
      - redis
    ports: []
    entrypoint: ""


volumes:
  bundle:
  rails_cache:
  redis_data:
  node_modules:
  development_db:
  test_db:

networks:
  components_structure_private_network:
    external: true
